version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      DB: ${DB}
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db-data: